name: shahd_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  getwidget: ^7.0.0
  go_router: ^16.2.4 
  http: ^1.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializer: ^0.2.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.7.2
  retrofit_generator: ^10.0.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
